#cloud-config
disk_setup:
  /dev/sdb:
    table_type: "gpt"
    layout:
      - [25, 82] # 25% för /var
      - [10, 82] # 10% för /home
      - [10, 82] # 10% för /tmp
    overwrite: true

fs_setup:
  - label: var_disk
    filesystem: "ext4"
    device: /dev/sdb1
  - label: home_disk
    filesystem: "ext4"
    device: /dev/sdb2
  - label: tmp_disk
    filesystem: "ext4"
    device: /dev/sdb3

mounts:
  - [/dev/sdb1, /var, "ext4", "defaults,rw,nosuid,nodev", "0", "2"]
  - [/dev/sdb2, /home, "ext4", "defaults,rw,nosuid,nodev", "0", "2"]
  - [/dev/sdb3, /tmp, "ext4", "defaults,rw,nosuid,nodev,noexec", "0", "2"]
