name: Terraform Destroy

on:
  workflow_dispatch: # Manuell trigger via GitHub UI
  # schedule:
  #   - cron: '0 22 * * 5'  # Fredag kväll — spara pengar på helgen

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Auth to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false # Rekommenderas för att undvika strul vid init/destroy

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
